/* AnalizadorSintactico.java */
/* Generated By:JavaCC: Do not edit this line. AnalizadorSintactico.java */
import java.util.*;
import java.io.*;

public class AnalizadorSintactico implements AnalizadorSintacticoConstants {
    private static List<ErrorInfo> errores = new ArrayList<>();
    private static Set<String> erroresRegistrados = new HashSet<>();

    public static void main(String[] args) throws Exception {
        try {
            AnalizadorSintactico analizador = new AnalizadorSintactico(System.in);
            analizador.Programa();

            if (errores.isEmpty()) {
                System.out.println("\u2713 Compilaci\u00f3n exitosa - No se encontraron errores");
            } else {
                System.out.println("\u2717 Compilaci\u00f3n fallida - Se encontraron " + errores.size() + " error(es):\n");

                Collections.sort(errores, new Comparator<ErrorInfo>() {
                    public int compare(ErrorInfo e1, ErrorInfo e2) {
                        if (e1.linea != e2.linea) {
                            return Integer.compare(e1.linea, e2.linea);
                        }
                        return Integer.compare(e1.columna, e2.columna);
                    }
                });

                for (ErrorInfo error : errores) {
                    System.out.println(error);
                }
                System.out.println("\nTotal de errores: " + errores.size());
            }

        } catch (TokenMgrError e) {
            System.out.println("\u2717 Error l\u00e9xico:");
            System.out.println(e.getMessage());
            System.exit(1);
        } catch (Exception e) {
            if (!errores.isEmpty()) {
                System.out.println("\u2717 Compilaci\u00f3n fallida - Se encontraron " + errores.size() + " error(es):\n");

                Collections.sort(errores, new Comparator<ErrorInfo>() {
                    public int compare(ErrorInfo e1, ErrorInfo e2) {
                        if (e1.linea != e2.linea) {
                            return Integer.compare(e1.linea, e2.linea);
                        }
                        return Integer.compare(e1.columna, e2.columna);
                    }
                });

                for (ErrorInfo error : errores) {
                    System.out.println(error);
                }
                System.out.println("\nTotal de errores: " + errores.size());
            } else {
                System.out.println("\u2717 Error fatal durante la compilaci\u00f3n:");
                System.out.println(e.getMessage());
            }
            System.exit(1);
        }

        if (!errores.isEmpty()) {
            System.exit(1);
        }
    }

    // Registra errores evitando duplicados
    private void agregarError(String tipo, Token t, String descripcion) {
        int lin = t.beginLine;
        int col = t.beginColumn;
        String clave = lin + ":" + col + ":" + descripcion;

        if (erroresRegistrados.contains(clave)) {
            return;
        }

        erroresRegistrados.add(clave);
        String ubicacion = "L\u00ednea " + lin + ", Columna " + col;
        String tokenTexto = "'" + t.image + "'";
        errores.add(new ErrorInfo(tipo, ubicacion, tokenTexto, descripcion, lin, col));
    }

    // Avanza hasta encontrar un token de recuperación
    private void avanzarHasta(int[] tokensDeRecuperacion) {
        Token actual;
        while (true) {
            actual = getToken(1);
            if (actual.kind == EOF) return;

            for (int tok : tokensDeRecuperacion) {
                if (actual.kind == tok) {
                    return;
                }
            }
            getNextToken();
        }
    }

    // Verifica si el siguiente token es el esperado, si no reporta error pero continúa
    private void esperarToken(int tipoEsperado, String nombreToken) {
        Token siguiente = getToken(1);
        if (siguiente.kind != tipoEsperado) {
            agregarError("ERROR_SINTACTICO", siguiente, "Se esperaba " + nombreToken);
        } else {
            getNextToken();
        }
    }

/* ========================
    REGLAS SINTÁCTICAS
    ======================== */
  final public 
void Programa() throws ParseException {Token t;
    boolean tokenInesperadoAntesDelFin = false;
    try {
      jj_consume_token(INICIO);
    } catch (ParseException e) {
agregarError("ERROR_SINT\u00c1CTICO", e.currentToken.next,
                    "El programa debe iniciar con 'inicio'");
        avanzarHasta(new int[]{ENTERO, REAL, CADENA_T, LOGICO, ID, SI, MIENTRAS, PARA, LEER, ESCRIBIR, RETORNAR, FIN});
    }
    label_1:
    while (true) {
      if (getToken(1).kind != FIN && getToken(1).kind != EOF) {
        ;
      } else {
        break label_1;
      }
      CodigoOError();
    }
t = getToken(1);
        if (t.kind != FIN && t.kind != EOF) {
            // Hay un token antes de FIN que no se procesó correctamente
            agregarError("ERROR_SINT\u00c1CTICO", t,
                        "Token inesperado, se esperaba 'fin'");
            tokenInesperadoAntesDelFin = true;
            // Consumir todos los tokens hasta FIN o EOF
            while (t.kind != FIN && t.kind != EOF) {
                t = getNextToken();
                if (getToken(1).kind == FIN || getToken(1).kind == EOF) {
                    break;
                }
            }
        }
    try {
      jj_consume_token(FIN);
    } catch (ParseException e) {
// Solo reportar si no hubo un token inesperado antes
        if (!tokenInesperadoAntesDelFin) {
            agregarError("ERROR_SINT\u00c1CTICO", e.currentToken.next,
                        "El programa debe finalizar con 'fin'");
        }
    }
    jj_consume_token(0);
}

  final public void CodigoOError() throws ParseException {Token t;
    try {
      if (jj_2_1(2147483647)) {
        Declaracion();
      } else if (jj_2_2(2)) {
        Sentencia();
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
// Si falla, verificar qué tipo de token es
        t = getToken(1);
        if (t.kind != EOF && t.kind != FIN) {
            t = getNextToken();
            agregarError("ERROR_SINT\u00c1CTICO", t,
                        "Token inesperado, se esperaba una declaraci\u00f3n o sentencia");
            avanzarHasta(new int[]{PUNTO_COMA, ENTERO, REAL, CADENA_T, LOGICO, ID, SI, MIENTRAS, PARA, LEER, ESCRIBIR, RETORNAR, FIN});
            if (getToken(1).kind == PUNTO_COMA) {
                getNextToken();
            }
        }
    }
}

  final public void Declaracion() throws ParseException {Token tipo, id, siguiente;
    tipo = TipoDato();
    try {
      id = jj_consume_token(ID);
    } catch (ParseException e) {
agregarError("ERROR_SINT\u00c1CTICO", e.currentToken.next,
                    "Falta identificador tras el tipo de dato");
        avanzarHasta(new int[]{PUNTO_COMA, ASIG});
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ASIG:{
      jj_consume_token(ASIG);
      try {
        Expresion();
      } catch (ParseException e) {
agregarError("ERROR_SINT\u00c1CTICO", e.currentToken.next,
                        "Expresi\u00f3n de asignaci\u00f3n incorrecta");
            avanzarHasta(new int[]{PUNTO_COMA});
      }
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      ;
    }
siguiente = getToken(1);
        if (siguiente.kind != PUNTO_COMA) {
            agregarError("ERROR_SINT\u00c1CTICO", siguiente, "Se esperaba punto y coma (;)");
        } else {
            getNextToken();
        }
}

  final public Token TipoDato() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ENTERO:{
      t = jj_consume_token(ENTERO);
      break;
      }
    case REAL:{
      t = jj_consume_token(REAL);
      break;
      }
    case CADENA_T:{
      t = jj_consume_token(CADENA_T);
      break;
      }
    case LOGICO:{
      t = jj_consume_token(LOGICO);
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return t;}
    throw new Error("Missing return statement in function");
}

  final public void Sentencia() throws ParseException {
    try {
      if (jj_2_3(2)) {
        Asignacion();
      } else if (jj_2_4(2)) {
        LecturaEscritura();
      } else if (jj_2_5(2)) {
        Condicional();
      } else if (jj_2_6(2)) {
        Ciclo();
      } else if (jj_2_7(2)) {
        Retorno();
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
agregarError("ERROR_SINT\u00c1CTICO", e.currentToken.next,
                    "Sentencia no reconocida");
        avanzarHasta(new int[]{PUNTO_COMA, LLAVE_CIERRA, ID, SI, MIENTRAS, PARA, LEER, ESCRIBIR, RETORNAR});
        if (getToken(1).kind == PUNTO_COMA) {
            getNextToken();
        }
    }
}

  final public void Asignacion() throws ParseException {Token id, sig;
    id = jj_consume_token(ID);
    try {
      jj_consume_token(ASIG);
    } catch (ParseException e) {
agregarError("ERROR_SINT\u00c1CTICO", e.currentToken.next,
                    "Se requiere operador de asignaci\u00f3n (=)");
        avanzarHasta(new int[]{PUNTO_COMA, NUM_ENTERO, NUM_REAL, CADENA, ID, PAR_ABRE});
    }
    try {
      Expresion();
    } catch (ParseException e) {
agregarError("ERROR_SINT\u00c1CTICO", e.currentToken.next,
                    "Expresi\u00f3n inv\u00e1lida en asignaci\u00f3n");
        avanzarHasta(new int[]{PUNTO_COMA});
    }
sig = getToken(1);
        if (sig.kind != PUNTO_COMA) {
            agregarError("ERROR_SINT\u00c1CTICO", sig, "Se esperaba punto y coma (;)");
        } else {
            getNextToken();
        }
}

  final public void LecturaEscritura() throws ParseException {Token sig;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case LEER:{
      jj_consume_token(LEER);
      try {
        jj_consume_token(PAR_ABRE);
        jj_consume_token(ID);
        jj_consume_token(PAR_CIERRA);
      } catch (ParseException e) {
agregarError("ERROR_SINT\u00c1CTICO", e.currentToken.next,
                        "Formato incorrecto: debe ser leer(variable);");
            avanzarHasta(new int[]{PUNTO_COMA});
      }
sig = getToken(1);
            if (sig.kind != PUNTO_COMA) {
                agregarError("ERROR_SINT\u00c1CTICO", sig, "Se esperaba punto y coma (;)");
            } else {
                getNextToken();
            }
      break;
      }
    case ESCRIBIR:{
      jj_consume_token(ESCRIBIR);
      try {
        jj_consume_token(PAR_ABRE);
        Expresion();
        label_2:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case COMA:{
            ;
            break;
            }
          default:
            jj_la1[2] = jj_gen;
            break label_2;
          }
          jj_consume_token(COMA);
          Expresion();
        }
        jj_consume_token(PAR_CIERRA);
      } catch (ParseException e) {
agregarError("ERROR_SINT\u00c1CTICO", e.currentToken.next,
                        "Error en sintaxis de 'escribir'");
            avanzarHasta(new int[]{PUNTO_COMA});
      }
sig = getToken(1);
            if (sig.kind != PUNTO_COMA) {
                agregarError("ERROR_SINT\u00c1CTICO", sig, "Se esperaba punto y coma (;)");
            } else {
                getNextToken();
            }
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void Condicional() throws ParseException {Token sig;
    jj_consume_token(SI);
    try {
      jj_consume_token(PAR_ABRE);
      ExpresionLogica();
      jj_consume_token(PAR_CIERRA);
    } catch (ParseException e) {
agregarError("ERROR_SINT\u00c1CTICO", e.currentToken.next,
                    "Condici\u00f3n mal formada en 'si'");
        avanzarHasta(new int[]{ENTONCES, LLAVE_ABRE});
    }
sig = getToken(1);
        if (sig.kind != ENTONCES) {
            agregarError("ERROR_SINT\u00c1CTICO", sig, "Falta 'entonces' tras la condici\u00f3n");
        } else {
            getNextToken();
        }
sig = getToken(1);
        if (sig.kind != LLAVE_ABRE) {
            agregarError("ERROR_SINT\u00c1CTICO", sig, "Se esperaba '{'");
        } else {
            getNextToken();
        }
    label_3:
    while (true) {
      if (getToken(1).kind != LLAVE_CIERRA && getToken(1).kind != EOF) {
        ;
      } else {
        break label_3;
      }
      Sentencia();
    }
sig = getToken(1);
        if (sig.kind != LLAVE_CIERRA) {
            agregarError("ERROR_SINT\u00c1CTICO", sig, "Se esperaba '}'");
        } else {
            getNextToken();
        }
    if (jj_2_8(2)) {
      jj_consume_token(SINO);
sig = getToken(1);
            if (sig.kind != LLAVE_ABRE) {
                agregarError("ERROR_SINT\u00c1CTICO", sig, "Se esperaba '{'");
            } else {
                getNextToken();
            }
      label_4:
      while (true) {
        if (getToken(1).kind != LLAVE_CIERRA && getToken(1).kind != EOF) {
          ;
        } else {
          break label_4;
        }
        Sentencia();
      }
sig = getToken(1);
            if (sig.kind != LLAVE_CIERRA) {
                agregarError("ERROR_SINT\u00c1CTICO", sig, "Se esperaba '}'");
            } else {
                getNextToken();
            }
    } else {
      ;
    }
}

  final public void Ciclo() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MIENTRAS:{
      CicloMientras();
      break;
      }
    case PARA:{
      CicloPara();
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void CicloMientras() throws ParseException {Token sig;
    jj_consume_token(MIENTRAS);
    try {
      jj_consume_token(PAR_ABRE);
      ExpresionLogica();
      jj_consume_token(PAR_CIERRA);
    } catch (ParseException e) {
agregarError("ERROR_SINT\u00c1CTICO", e.currentToken.next,
                    "Condici\u00f3n incorrecta en 'mientras'");
        avanzarHasta(new int[]{HACER, LLAVE_ABRE});
    }
sig = getToken(1);
        if (sig.kind != HACER) {
            agregarError("ERROR_SINT\u00c1CTICO", sig, "Se esperaba 'hacer'");
        } else {
            getNextToken();
        }
sig = getToken(1);
        if (sig.kind != LLAVE_ABRE) {
            agregarError("ERROR_SINT\u00c1CTICO", sig, "Se esperaba '{'");
        } else {
            getNextToken();
        }
    label_5:
    while (true) {
      if (getToken(1).kind != LLAVE_CIERRA && getToken(1).kind != EOF) {
        ;
      } else {
        break label_5;
      }
      Sentencia();
    }
sig = getToken(1);
        if (sig.kind != LLAVE_CIERRA) {
            agregarError("ERROR_SINT\u00c1CTICO", sig, "Se esperaba '}'");
        } else {
            getNextToken();
        }
}

  final public void CicloPara() throws ParseException {Token sig;
    jj_consume_token(PARA);
    try {
      jj_consume_token(PAR_ABRE);
      jj_consume_token(ID);
      jj_consume_token(ASIG);
      Expresion();
      jj_consume_token(PUNTO_COMA);
      ExpresionLogica();
      jj_consume_token(PUNTO_COMA);
      jj_consume_token(ID);
      jj_consume_token(ASIG);
      Expresion();
      jj_consume_token(PAR_CIERRA);
    } catch (ParseException e) {
agregarError("ERROR_SINT\u00c1CTICO", e.currentToken.next,
                    "Estructura incorrecta en ciclo 'para'");
        avanzarHasta(new int[]{HACER, LLAVE_ABRE});
    }
sig = getToken(1);
        if (sig.kind != HACER) {
            agregarError("ERROR_SINT\u00c1CTICO", sig, "Se esperaba 'hacer'");
        } else {
            getNextToken();
        }
sig = getToken(1);
        if (sig.kind != LLAVE_ABRE) {
            agregarError("ERROR_SINT\u00c1CTICO", sig, "Se esperaba '{'");
        } else {
            getNextToken();
        }
    label_6:
    while (true) {
      if (getToken(1).kind != LLAVE_CIERRA && getToken(1).kind != EOF) {
        ;
      } else {
        break label_6;
      }
      Sentencia();
    }
sig = getToken(1);
        if (sig.kind != LLAVE_CIERRA) {
            agregarError("ERROR_SINT\u00c1CTICO", sig, "Se esperaba '}'");
        } else {
            getNextToken();
        }
}

  final public void Retorno() throws ParseException {Token sig;
    jj_consume_token(RETORNAR);
    try {
      Expresion();
    } catch (ParseException e) {
agregarError("ERROR_SINT\u00c1CTICO", e.currentToken.next,
                    "Expresi\u00f3n de retorno inv\u00e1lida");
        avanzarHasta(new int[]{PUNTO_COMA});
    }
sig = getToken(1);
        if (sig.kind != PUNTO_COMA) {
            agregarError("ERROR_SINT\u00c1CTICO", sig, "Se esperaba punto y coma (;)");
        } else {
            getNextToken();
        }
}

  final public void Expresion() throws ParseException {
    ExpresionLogica();
}

  final public void ExpresionLogica() throws ParseException {
    ExpresionRelacional();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AND:
      case OR:{
        ;
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        break label_7;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AND:{
        jj_consume_token(AND);
        break;
        }
      case OR:{
        jj_consume_token(OR);
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      try {
        ExpresionRelacional();
      } catch (ParseException e) {
agregarError("ERROR_SINT\u00c1CTICO", e.currentToken.next,
                        "Error en operaci\u00f3n l\u00f3gica");
            avanzarHasta(new int[]{PUNTO_COMA, PAR_CIERRA, LLAVE_CIERRA});
      }
    }
}

  final public void ExpresionRelacional() throws ParseException {
    ExpresionAritmetica();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MENOR_IGUAL:
    case MAYOR_IGUAL:
    case DIFERENTE:
    case IGUAL:
    case MENOR:
    case MAYOR:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MENOR:{
        jj_consume_token(MENOR);
        break;
        }
      case MAYOR:{
        jj_consume_token(MAYOR);
        break;
        }
      case MENOR_IGUAL:{
        jj_consume_token(MENOR_IGUAL);
        break;
        }
      case MAYOR_IGUAL:{
        jj_consume_token(MAYOR_IGUAL);
        break;
        }
      case IGUAL:{
        jj_consume_token(IGUAL);
        break;
        }
      case DIFERENTE:{
        jj_consume_token(DIFERENTE);
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      try {
        ExpresionAritmetica();
      } catch (ParseException e) {
agregarError("ERROR_SINT\u00c1CTICO", e.currentToken.next,
                        "Error en comparaci\u00f3n");
            avanzarHasta(new int[]{PUNTO_COMA, PAR_CIERRA, LLAVE_CIERRA, AND, OR});
      }
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      ;
    }
}

  final public void ExpresionAritmetica() throws ParseException {
    Termino();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SUMA:
      case RESTA:{
        ;
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        break label_8;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SUMA:{
        jj_consume_token(SUMA);
        break;
        }
      case RESTA:{
        jj_consume_token(RESTA);
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      try {
        Termino();
      } catch (ParseException e) {
agregarError("ERROR_SINT\u00c1CTICO", e.currentToken.next,
                        "Error en operaci\u00f3n aritm\u00e9tica");
            avanzarHasta(new int[]{PUNTO_COMA, PAR_CIERRA, LLAVE_CIERRA});
      }
    }
}

  final public void Termino() throws ParseException {
    Factor();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULTIPLICA:
      case DIVIDE:{
        ;
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        break label_9;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULTIPLICA:{
        jj_consume_token(MULTIPLICA);
        break;
        }
      case DIVIDE:{
        jj_consume_token(DIVIDE);
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      try {
        Factor();
      } catch (ParseException e) {
agregarError("ERROR_SINT\u00c1CTICO", e.currentToken.next,
                        "Error en multiplicaci\u00f3n/divisi\u00f3n");
            avanzarHasta(new int[]{PUNTO_COMA, PAR_CIERRA, LLAVE_CIERRA, SUMA, RESTA});
      }
    }
}

  final public void Factor() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NUM_ENTERO:{
        jj_consume_token(NUM_ENTERO);
        break;
        }
      case NUM_REAL:{
        jj_consume_token(NUM_REAL);
        break;
        }
      case CADENA:{
        jj_consume_token(CADENA);
        break;
        }
      case VERDADERO:{
        jj_consume_token(VERDADERO);
        break;
        }
      case FALSO:{
        jj_consume_token(FALSO);
        break;
        }
      case ID:{
        jj_consume_token(ID);
        break;
        }
      case PAR_ABRE:{
        jj_consume_token(PAR_ABRE);
        Expresion();
        jj_consume_token(PAR_CIERRA);
        break;
        }
      case NOT:{
        jj_consume_token(NOT);
        Factor();
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
agregarError("ERROR_SINT\u00c1CTICO", e.currentToken.next,
                    "Factor no v\u00e1lido");
        avanzarHasta(new int[]{PUNTO_COMA, PAR_CIERRA, LLAVE_CIERRA, SUMA, RESTA, MULTIPLICA, DIVIDE});
    }
}

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_7()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_8()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_3_2()
 {
    if (jj_3R_Sentencia_336_5_11()) return true;
    return false;
  }

  private boolean jj_3R_Condicional_501_13_17()
 {
    if (jj_3R_Sentencia_336_5_11()) return true;
    return false;
  }

  private boolean jj_3R_LecturaEscritura_414_5_19()
 {
    if (jj_scan_token(ESCRIBIR)) return true;
    if (jj_scan_token(PAR_ABRE)) return true;
    return false;
  }

  private boolean jj_3R_Factor_732_15_31()
 {
    if (jj_scan_token(NOT)) return true;
    return false;
  }

  private boolean jj_3R_Factor_731_15_30()
 {
    if (jj_scan_token(PAR_ABRE)) return true;
    return false;
  }

  private boolean jj_3R_ExpresionAritmetica_691_5_27()
 {
    if (jj_3R_Termino_707_5_28()) return true;
    return false;
  }

  private boolean jj_3R_Asignacion_359_5_12()
 {
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(ASIG)) return true;
    return false;
  }

  private boolean jj_3_7()
 {
    if (jj_3R_Retorno_630_5_16()) return true;
    return false;
  }

  private boolean jj_3_6()
 {
    if (jj_3R_Ciclo_519_5_15()) return true;
    return false;
  }

  private boolean jj_3_8()
 {
    if (jj_scan_token(SINO)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Condicional_501_13_17()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3_5()
 {
    if (jj_3R_Condicional_443_5_14()) return true;
    return false;
  }

  private boolean jj_3_4()
 {
    if (jj_3R_LecturaEscritura_392_5_13()) return true;
    return false;
  }

  private boolean jj_3R_Condicional_443_5_14()
 {
    if (jj_scan_token(SI)) return true;
    if (jj_scan_token(PAR_ABRE)) return true;
    return false;
  }

  private boolean jj_3R_Retorno_630_5_16()
 {
    if (jj_scan_token(RETORNAR)) return true;
    if (jj_3R_Expresion_653_5_22()) return true;
    return false;
  }

  private boolean jj_3R_Factor_723_5_29()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(44)) {
    jj_scanpos = xsp;
    if (jj_scan_token(43)) {
    jj_scanpos = xsp;
    if (jj_scan_token(45)) {
    jj_scanpos = xsp;
    if (jj_scan_token(5)) {
    jj_scanpos = xsp;
    if (jj_scan_token(6)) {
    jj_scanpos = xsp;
    if (jj_scan_token(46)) {
    jj_scanpos = xsp;
    if (jj_3R_Factor_731_15_30()) {
    jj_scanpos = xsp;
    if (jj_3R_Factor_732_15_31()) return true;
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_ExpresionRelacional_675_5_26()
 {
    if (jj_3R_ExpresionAritmetica_691_5_27()) return true;
    return false;
  }

  private boolean jj_3_3()
 {
    if (jj_3R_Asignacion_359_5_12()) return true;
    return false;
  }

  private boolean jj_3R_LecturaEscritura_392_5_13()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_LecturaEscritura_392_5_18()) {
    jj_scanpos = xsp;
    if (jj_3R_LecturaEscritura_414_5_19()) return true;
    }
    return false;
  }

  private boolean jj_3R_LecturaEscritura_392_5_18()
 {
    if (jj_scan_token(LEER)) return true;
    if (jj_scan_token(PAR_ABRE)) return true;
    return false;
  }

  private boolean jj_3R_CicloPara_578_5_24()
 {
    if (jj_scan_token(PARA)) return true;
    if (jj_scan_token(PAR_ABRE)) return true;
    return false;
  }

  private boolean jj_3R_CicloMientras_528_5_23()
 {
    if (jj_scan_token(MIENTRAS)) return true;
    if (jj_scan_token(PAR_ABRE)) return true;
    return false;
  }

  private boolean jj_3R_Sentencia_336_5_11()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_3()) {
    jj_scanpos = xsp;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3_6()) {
    jj_scanpos = xsp;
    if (jj_3_7()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_Ciclo_520_7_21()
 {
    if (jj_3R_CicloPara_578_5_24()) return true;
    return false;
  }

  private boolean jj_3R_Termino_707_5_28()
 {
    if (jj_3R_Factor_723_5_29()) return true;
    return false;
  }

  private boolean jj_3R_Ciclo_519_5_20()
 {
    if (jj_3R_CicloMientras_528_5_23()) return true;
    return false;
  }

  private boolean jj_3R_Ciclo_519_5_15()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Ciclo_519_5_20()) {
    jj_scanpos = xsp;
    if (jj_3R_Ciclo_520_7_21()) return true;
    }
    return false;
  }

  private boolean jj_3R_ExpresionLogica_659_5_25()
 {
    if (jj_3R_ExpresionRelacional_675_5_26()) return true;
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_3R_TipoDato_327_5_10()) return true;
    if (jj_scan_token(ID)) return true;
    return false;
  }

  private boolean jj_3R_TipoDato_327_5_10()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(1)) {
    jj_scanpos = xsp;
    if (jj_scan_token(2)) {
    jj_scanpos = xsp;
    if (jj_scan_token(3)) {
    jj_scanpos = xsp;
    if (jj_scan_token(4)) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_Expresion_653_5_22()
 {
    if (jj_3R_ExpresionLogica_659_5_25()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public AnalizadorSintacticoTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[14];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x0,0x1e,0x0,0x180,0x3000,0x180000,0x180000,0xfc000000,0xfc000000,0xc00000,0xc00000,0x3000000,0x3000000,0x200060,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x1,0x0,0x100,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x7802,};
	}
  final private JJCalls[] jj_2_rtns = new JJCalls[8];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public AnalizadorSintactico(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public AnalizadorSintactico(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new AnalizadorSintacticoTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public AnalizadorSintactico(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new AnalizadorSintacticoTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new AnalizadorSintacticoTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public AnalizadorSintactico(AnalizadorSintacticoTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(AnalizadorSintacticoTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 14; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[51];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 14; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 51; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 8; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			   case 5: jj_3_6(); break;
			   case 6: jj_3_7(); break;
			   case 7: jj_3_8(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}

class ErrorInfo {
    String tipo;
    String donde;
    String cual;
    String solucion;
    int linea;
    int columna;

    ErrorInfo(String tipo, String donde, String cual, String solucion, int linea, int columna) {
        this.tipo = tipo;
        this.donde = donde;
        this.cual = cual;
        this.solucion = solucion;
        this.linea = linea;
        this.columna = columna;
    }

    @Override
    public String toString() {
        return donde + ": " + tipo.replace("_", " ") + " " + cual + " - " + solucion;
    }
}
